import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {NPC_HEIGHT_M,KING_HEIGHT_M,KING_REGALIA_SCALE,KING_REGALIA,KING_CAMERA} from '../src/presentation.js';

const ratio=KING_HEIGHT_M/NPC_HEIGHT_M;
assert.ok(ratio>=1.03&&ratio<=1.07,'king must be only slightly taller than living NPCs');
assert.ok(KING_HEIGHT_M<=1.82,'king may not regress to oversized world scale');
assert.ok(Math.abs(KING_REGALIA_SCALE-1)<.01,'regalia is authored directly for the NPC-family king');
assert.ok(KING_REGALIA.pauldronRadius<=.09,'royal shoulder detail must not dwarf the NPC-family torso');
assert.ok(KING_REGALIA.capeTopHalfWidth<=.23&&KING_REGALIA.capeBottomHalfWidth<=.31,'cape must remain inside a human-scale silhouette');
assert.ok(KING_REGALIA.capeTopY<=1.45,'cape must begin below the head so the king head stays visible');
assert.ok(KING_REGALIA.crownRadius<=.11&&KING_REGALIA.crownSpikeHeight<=.10,'crown must fit the head rather than become a floating prop');
assert.ok(KING_CAMERA.fov>=64&&KING_CAMERA.fov<=70,'camera FOV must retain useful environment context');
assert.equal(KING_CAMERA.defaultMode,'third','mobile gameplay must start in third person');
assert.ok(KING_CAMERA.third.standingDistance>=4.2&&KING_CAMERA.third.standingDistance<=4.8,'third-person camera should be close but retain full-body framing');
assert.ok(KING_CAMERA.third.defaultPitch>=.04&&KING_CAMERA.third.defaultPitch<=.12,'default third-person pitch should sit near shoulder height');
assert.ok(KING_CAMERA.third.maxPitch<=.28,'third-person pitch must prevent the overhead V15 view');
assert.ok(KING_CAMERA.third.minPitch>=-.08,'third-person camera must not swing below an impractical low angle');
assert.ok(KING_CAMERA.look.yawSensitivity<=.0055&&KING_CAMERA.look.pitchSensitivity<=.004,'touch look sensitivity must be controlled on mobile');
assert.ok(KING_CAMERA.look.angleDamping>=10,'camera angles must use visible damping rather than direct snapping');
assert.ok(KING_CAMERA.first.eyeHeight>=1.55&&KING_CAMERA.first.eyeHeight<=1.68,'first-person eye height must sit inside a normal adult head range');
const nominalBodyFraction=KING_HEIGHT_M/(2*KING_CAMERA.third.standingDistance*Math.tan((KING_CAMERA.fov*Math.PI/180)/2));
assert.ok(nominalBodyFraction>=.29&&nominalBodyFraction<=.36,'third-person full body should remain readable without clipping');

console.log(JSON.stringify({ok:true,NPC_HEIGHT_M,KING_HEIGHT_M,ratio,nominalBodyFraction,KING_REGALIA_SCALE,KING_CAMERA},null,2));
const gameSource=readFileSync(new URL('../src/game.js',import.meta.url),'utf8');
const cssSource=readFileSync(new URL('../src/style.css',import.meta.url),'utf8');
assert.match(gameSource,/if\(n==='head'\)kingHead=o/,'runtime must capture the animated head node');
assert.match(gameSource,/kingHead\.add\(crown\)/,'crown must be attached to the animated head');
assert.match(gameSource,/n==='face'\|\|n==='hair'\|\|n==='weapon'/,'guard helmet shells and guard spear must be removed from the king base');
assert.match(cssSource,/@media \(orientation:landscape\)/,'landscape HUD override must exist');
assert.match(cssSource,/#objective\{top:58px\}/,'landscape objective must be raised');