import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {NPC_HEIGHT_M,KING_HEIGHT_M,KING_REGALIA_SCALE,KING_REGALIA,KING_CAMERA} from '../src/presentation.js';

const ratio=KING_HEIGHT_M/NPC_HEIGHT_M;
assert.ok(ratio>=1.03&&ratio<=1.07,'king must be only slightly taller than living NPCs');
assert.ok(KING_HEIGHT_M<=1.82,'king may not regress to oversized world scale');
assert.ok(Math.abs(KING_REGALIA_SCALE-1)<.01,'regalia is authored directly for the NPC-family king');
assert.ok(KING_REGALIA.pauldronRadius<=.07,'legacy pauldron limit remains bounded even though V19 uses fitted model shoulders');
assert.ok(KING_REGALIA.capeTopHalfWidth<=.19&&KING_REGALIA.capeBottomHalfWidth<=.25,'cape must remain inside a human-scale silhouette');
assert.ok(KING_REGALIA.capeTopY<=1.45,'cape must begin below the head so the king head stays visible');
assert.ok(KING_REGALIA.crownRadius>=.12&&KING_REGALIA.crownRadius<=.14,'crown band must be wide enough to read on the measured guard head');
assert.ok(KING_REGALIA.crownSpikeHeight>=.10&&KING_REGALIA.crownSpikeHeight<=.12,'crown spikes must be visible without becoming oversized');
assert.ok(KING_REGALIA.crownHeadOffset>=.27&&KING_REGALIA.crownHeadOffset<=.29,'crown must sit at the measured top of the guard head rather than inside it');
assert.ok(KING_CAMERA.fov>=64&&KING_CAMERA.fov<=70,'camera FOV must retain useful environment context');
assert.equal(KING_CAMERA.defaultMode,'third','mobile gameplay must start in third person');
assert.ok(KING_CAMERA.third.standingDistance>=3.7&&KING_CAMERA.third.standingDistance<=4.1,'third-person camera should be close enough for mobile character readability');
assert.ok(KING_CAMERA.third.defaultPitch>=.04&&KING_CAMERA.third.defaultPitch<=.12,'default third-person pitch should sit near shoulder height');
assert.ok(KING_CAMERA.third.maxPitch<=.28,'third-person pitch must prevent the overhead V15 view');
assert.ok(KING_CAMERA.third.minPitch>=-.08,'third-person camera must not swing below an impractical low angle');
assert.ok(KING_CAMERA.look.yawSensitivity<=.0055&&KING_CAMERA.look.pitchSensitivity<=.004,'touch look sensitivity must be controlled on mobile');
assert.ok(KING_CAMERA.look.angleDamping>=10,'camera angles must use visible damping rather than direct snapping');
assert.ok(KING_CAMERA.first.eyeHeight>=1.55&&KING_CAMERA.first.eyeHeight<=1.68,'first-person eye height must sit inside a normal adult head range');
const nominalBodyFraction=KING_HEIGHT_M/(2*KING_CAMERA.third.standingDistance*Math.tan((KING_CAMERA.fov*Math.PI/180)/2));
assert.ok(nominalBodyFraction>=.34&&nominalBodyFraction<=.39,'third-person full body should be larger while retaining head/feet margin');

console.log(JSON.stringify({ok:true,NPC_HEIGHT_M,KING_HEIGHT_M,ratio,nominalBodyFraction,KING_REGALIA_SCALE,KING_CAMERA},null,2));
const gameSource=readFileSync(new URL('../src/game.js',import.meta.url),'utf8');
const cssSource=readFileSync(new URL('../src/style.css',import.meta.url),'utf8');
assert.match(gameSource,/if\(n==='head'\)kingHead=o/,'runtime must capture the animated head node');
assert.match(gameSource,/crown\.position\.set\(0,KING_REGALIA\.crownHeadOffset,0\);kingHead\.add\(crown\)/,'crown must be placed above and attached to the animated head');
assert.doesNotMatch(gameSource,/crown\.scale\.setScalar\(inv\)/,'crown must not use the obsolete inverse-scale transform');
assert.match(gameSource,/g\.name='royal-crown'/,'crown must have an explicit runtime identity');
assert.match(gameSource,/torso\.attach\(royalRegalia\)/,'royal clothing must follow the animated torso');
assert.match(gameSource,/function resizeView\(\)/,'camera must update renderer size and aspect on device rotation');
assert.match(gameSource,/fitCharacterHeight\(playerVisual,KING_HEIGHT_M\)/,'player scale must be fitted from humanoid body bounds rather than held equipment');
assert.match(gameSource,/n==='face'\|\|n==='hair'\|\|n\.startsWith\('weapon'\)/,'guard helmet shells and every guard-weapon descendant must be hidden from the king base');
assert.match(cssSource,/@media \(orientation:landscape\)/,'landscape HUD override must exist');
assert.match(cssSource,/#objective\{top:54px;padding:5px 11px\}/,'landscape objective must be raised');
const livingSource=readFileSync(new URL('../src/render/living.js',import.meta.url),'utf8');
const boundsSource=readFileSync(new URL('../src/render/characterBounds.js',import.meta.url),'utf8');
assert.match(livingSource,/fitCharacterHeight\(visual,1\.72\)/,'living guards must use the same body-only height rule');
assert.match(boundsSource,/name\.startsWith\(p\)/,'body bounds must exclude weapon ancestry');
assert.doesNotMatch(gameSource,/new THREE\.SphereGeometry\(KING_REGALIA\.pauldronRadius/,'king must not add detached procedural pauldrons');
assert.doesNotMatch(gameSource,/new THREE\.CylinderGeometry\(\.016,\.020,\.38/,'king must not add a detached procedural scabbard');
