// Role schedules for non-military inhabitants. Each planner maps (actor, hour) -> memoised plan.
import {S,day,season} from './core.js';
import {plan,registerPlanner,actors} from './actors.js';
import {byId,AREAS} from '../layout.js';

export const courtOpen=h=>(h>=9&&h<12)||(h>=15&&h<17);
export const sched=(h,tbl)=>{for(const [f,t,fn] of tbl){if(f<=t?(h>=f&&h<t):(h>=f||h<t))return fn}return tbl[tbl.length-1][2]};
const PN={plaza:'the Royal Court',market:'the market',yard:'the training yard',gate:'the main gate',villageSquare:'the village square',lumber:'the lumber camp',mine:'the mine',ash:'the camp fire',bmYard:'the keep yard',bmGate:'the Blackmere gate',bridge:'Kingsbridge',wall:'the walls',fields:'the fields',f1:'the fields',f2:'the fields',f3:'the fields',f4:'the fields',mbfield:'the Millbrook plots'};
export const nm=id=>byId[id]?.name||PN[id]||id;
const K=(s,a)=>s+'#'+a.id;
export const sleepPlan=a=>plan(K('sleep',a),()=>({seq:[{place:a.home,spot:a.bedSlot||'bed',i:a.bedIdx,dur:1e9,pose:'sleep',label:'Asleep in the '+nm(a.home)}]}));
export const eatPlan=(a,place)=>plan(K('eat:'+place,a),()=>({seq:[{place,spot:'seat',i:a.idx,dur:1e9,pose:'sit',hook:'eat',label:'Eating a meal in '+nm(place)}]}));
export const stayPlan=(a,place,spot,pose,label,o={})=>plan(K(`stay:${place}:${spot}:${pose}:${o.i??''}:${label}:${o.hook??''}:${o.carry??''}:${o.y??''}`,a),()=>({seq:[{place,spot,i:o.i??a.idx,dur:1e9,pose,label,...o}]}));
export const loopPlan=(key,build)=>plan(key,()=>({seq:build()}));
const homeStand=(a,label)=>stayPlan(a,a.home,'seat','sit',label||'Resting at home');
const tavernSocial=(a)=>plan(K('tavern',a),()=>({seq:[{place:'tavern',spot:'seat',i:a.idx,dur:40+a.idx%5*8,pose:'sit',label:'Drinking and talking at the Gilded Boar',hook:'social'},{place:'tavern',spot:'bar',dur:25,pose:'talk',label:'Chatting with the keeper'},{place:'tavern',spot:'seat',i:a.idx+3,dur:50,pose:'sit',label:'Sharing gossip at the Gilded Boar',hook:'social'}]}));
export const isWinter=()=>season()===3;

// ---- helpers for work loops -----------------------------------------------------------------------
const fieldWork=(a)=>plan(K('field',a),()=>({seq:[0,1,2].map(k=>({place:a.work,spot:'hoe',i:a.idx*3+k,dur:38+k*6,pose:'hoe',label:'Tending the crops',prod:'grain'}))}));
const chores=(a)=>plan(K('chores',a),()=>({seq:[{place:'villageSquare',spot:'stand',i:a.idx,dur:30,pose:'hammer',label:'Mending fences and tools'},{place:'villageSquare',spot:'well',dur:22,pose:'carry',carry:'basket',label:'Drawing water at the well'}]}));
const carterGrain=(a)=>plan(K('cartG',a),()=>({seq:[{place:a.work||'f1',spot:'hoe',i:a.idx,dur:7,pose:'stand',label:'Loading the grain cart',hook:'pickGrain'},{place:'granary',spot:'store',i:a.idx,dur:7,pose:'carry',carry:'sack',label:'Hauling grain to the Royal Granary',hook:'dropGrain'}]}));
const carterWood=(a)=>plan(K('cartW',a),()=>({seq:[{place:'lumber',spot:'pile',dur:7,pose:'stand',label:'Loading cut timber',hook:'pickWood'},{place:'smithy',spot:'store',dur:7,pose:'carry',carry:'log',label:'Hauling timber to the castle',hook:'dropWood'}]}));
const kitchenWork=(a)=>plan(K('kitchen',a),()=>({seq:[{place:'kitchens',spot:'cook',i:a.idx,dur:40,pose:'cook',label:'Cooking for the household',prod:'meals'},{place:'kitchens',spot:'prep',i:a.idx,dur:34,pose:'write',label:'Kneading bread and preparing meals'},{place:'kitchens',spot:'store',dur:12,pose:'carry',carry:'sack',label:'Fetching flour from the stores'}]}));
const serveHall=(a)=>plan(K('serve',a),()=>({seq:[{place:'kitchens',spot:'store',dur:9,pose:'carry',carry:'tray',label:'Loading trays in the kitchens'},{place:'greatHall',spot:'stand',i:a.idx,dur:14,pose:'carry',carry:'tray',label:'Serving trays in the Great Hall'},{place:'plaza',spot:'servant',i:a.idx,dur:16,pose:'stand',label:'Waiting on the court'}]}));
const sweepPlaza=(a)=>plan(K('sweep',a),()=>({seq:[0,1,2].map(k=>({place:'plaza',spot:'sweep',i:a.idx+k*2,dur:26,pose:'sweep',label:'Sweeping the royal court'}))}));
const sweepHall=(a)=>plan(K('sweepH',a),()=>({seq:[{place:'greatHall',spot:'stand',i:a.idx,dur:28,pose:'sweep',label:'Cleaning the Great Hall'},{place:'apartments',spot:'stand',dur:26,pose:'sweep',label:'Tidying the royal apartments'},{place:'lodgings',spot:'rest',i:a.idx,dur:22,pose:'sweep',label:'Airing the lodgings'}]}));
const smithing=(a)=>plan(K('smith',a),()=>({seq:[{place:'smithy',spot:'forge',dur:24,pose:'stand',label:'Working the bellows',prod:'arms'},{place:'smithy',spot:'anvil',i:a.idx,dur:44,pose:'hammer',label:'Hammering arms at the anvil',prod:'arms'},{place:'smithy',spot:'store',dur:10,pose:'carry',carry:'crate',label:'Stocking the armory racks'}]}));
const stablework=(a)=>plan(K('stable',a),()=>({seq:[{place:'stable',spot:'tend',i:a.idx,dur:30,pose:'tend',label:'Grooming the royal horses'},{place:'stable',spot:'tend',i:a.idx+1,dur:26,pose:'sweep',label:'Mucking out the stalls'}]}));
const wander=(a,key,place,spot,pose,label,n=4)=>plan(K(key,a),()=>({seq:Array.from({length:n},(_,k)=>({place,spot,i:a.idx*2+k*3,dur:20+k*5,pose,label}))}));
const inspect=(a,stops)=>plan(K('inspect',a),()=>({seq:stops.map((s,k)=>({place:s[0],spot:s[1]||'stand',i:s[3]??a.idx,dur:s[2]||30,pose:s[4]||'talk',label:s[5]||('Inspecting '+nm(s[0]))}))}));

// ---- royal household ---------------------------------------------------------------------------------
registerPlanner('cook',(a,h)=>sched(h,[[22,4.5,()=>sleepPlan(a)],[4.5,12,()=>kitchenWork(a)],[12,13,()=>eatPlan(a,'greatHall')],[13,19,()=>kitchenWork(a)],[19,20,()=>eatPlan(a,'greatHall')],[20,22,()=>stayPlan(a,'greatHall','stand','talk','Resting in the Great Hall')]])());
registerPlanner('kitchenhand',(a,h)=>sched(h,[[22,5,()=>sleepPlan(a)],[5,7,()=>kitchenWork(a)],[7,8,()=>eatPlan(a,'greatHall')],[8,11,()=>serveHall(a)],[11,12,()=>serveHall(a)],[12,13,()=>eatPlan(a,'greatHall')],[13,18,()=>kitchenWork(a)],[18,20,()=>serveHall(a)],[20,22,()=>stayPlan(a,'kitchens','stand','sit','Resting by the hearth')]])());
registerPlanner('servant',(a,h)=>sched(h,[[22,5.5,()=>sleepPlan(a)],[5.5,7,()=>sweepPlaza(a)],[7,8,()=>eatPlan(a,'greatHall')],[8,11.5,()=>serveHall(a)],[11.5,12,()=>serveHall(a)],[12,13,()=>eatPlan(a,'greatHall')],[13,17,()=>sweepHall(a)],[17,19,()=>serveHall(a)],[19,20,()=>eatPlan(a,'greatHall')],[20,22,()=>stayPlan(a,'greatHall','stand','talk','Resting in the Great Hall')]])());
registerPlanner('maid',(a,h)=>sched(h,[[22,5.5,()=>sleepPlan(a)],[5.5,7,()=>sweepHall(a)],[7,8,()=>eatPlan(a,'greatHall')],[8,12,()=>sweepHall(a)],[12,13,()=>eatPlan(a,'greatHall')],[13,18,()=>sweepPlaza(a)],[18,19,()=>eatPlan(a,'greatHall')],[19,22,()=>stayPlan(a,'lodgings','rest','sit','Resting in the lodgings')]])());
registerPlanner('stablehand',(a,h)=>sched(h,[[21.5,5,()=>sleepPlan(a)],[5,7,()=>stablework(a)],[7,8,()=>eatPlan(a,'greatHall')],[8,12,()=>stablework(a)],[12,13,()=>eatPlan(a,'greatHall')],[13,19,()=>stablework(a)],[19,21.5,()=>stayPlan(a,'stable','stand','sit','Resting in the stable')]])());
registerPlanner('smith',(a,h)=>sched(h,[[21.5,5.5,()=>sleepPlan(a)],[5.5,6.5,()=>eatPlan(a,'greatHall')],[6.5,12,()=>smithing(a)],[12,13,()=>eatPlan(a,'greatHall')],[13,18,()=>smithing(a)],[18,19,()=>eatPlan(a,'greatHall')],[19,21.5,()=>stayPlan(a,'smithy','stand','sit','Resting by the forge')]])());
registerPlanner('apprentice',(a,h)=>sched(h,[[21.5,5.5,()=>sleepPlan(a)],[5.5,6.5,()=>eatPlan(a,'greatHall')],[6.5,12,()=>smithing(a)],[12,13,()=>eatPlan(a,'greatHall')],[13,18,()=>smithing(a)],[18,19,()=>eatPlan(a,'greatHall')],[19,21.5,()=>stayPlan(a,'smithy','stand','sit','Cleaning tools')]])());
registerPlanner('priest',(a,h)=>sched(h,[[22,5,()=>sleepPlan(a)],[5,6.5,()=>stayPlan(a,'chapel','altar','pray','Morning prayers at the altar')],[6.5,7.5,()=>eatPlan(a,'greatHall')],[7.5,12,()=>plan(K('pTend',a),()=>({seq:[{place:'chapel',spot:'tend',dur:40,pose:'tend',label:'Tending the infirmary'},{place:'chapel',spot:'pew',i:a.idx,dur:30,pose:'pray',label:'Praying with the faithful'}]}))],[12,13,()=>eatPlan(a,'greatHall')],[13,17,()=>inspect(a,[['plaza','stand',35,0,'talk','Blessing the court'],['market','browse',30,1,'talk','Speaking with the townsfolk'],['chapel','stand',30,0,'talk','Counselling penitents']])],[17,18.5,()=>stayPlan(a,'chapel','altar','pray','Evening prayers')],[18.5,19.5,()=>eatPlan(a,'greatHall')],[19.5,22,()=>stayPlan(a,'chapel','pew','sit','Reading scripture')]])());
registerPlanner('healer',(a,h)=>sched(h,[[22,6,()=>sleepPlan(a)],[6,7,()=>eatPlan(a,'greatHall')],[7,11,()=>plan(K('hTend',a),()=>({seq:[{place:'chapel',spot:'tend',dur:38,pose:'tend',label:'Tending the wounded'},{place:'yard',spot:'rest',i:a.idx,dur:30,pose:'tend',label:'Treating soldiers in the yard',hook:'heal'}]}))],[11,12,()=>eatPlan(a,'greatHall')],[12,17,()=>plan(K('hTend2',a),()=>({seq:[{place:'chapel',spot:'tend',dur:38,pose:'tend',label:'Preparing poultices'},{place:'barracksA',spot:'rest',dur:26,pose:'tend',label:'Visiting the sick in barracks',hook:'heal'}]}))],[17,19,()=>stayPlan(a,'chapel','stand','stand','Keeping vigil in the infirmary')],[19,20,()=>eatPlan(a,'greatHall')],[20,22,()=>stayPlan(a,'chapel','pew','sit','Resting in the chapel')]])());
registerPlanner('treasurer',(a,h)=>sched(h,[[22,6.5,()=>sleepPlan(a)],[6.5,7.5,()=>eatPlan(a,'greatHall')],[8,12,()=>stayPlan(a,'treasury','desk','write','Reckoning the treasury ledgers',{i:0})],[12,13,()=>eatPlan(a,'greatHall')],[13,17,()=>plan(K('trs',a),()=>({seq:[{place:'treasury',spot:'desk',i:0,dur:60,pose:'write',label:'Writing the daily ledger'},{place:'treasury',spot:'chest',dur:30,pose:'carry',carry:'crate',label:'Counting coin in the strongroom'}]}))],[17,19,()=>stayPlan(a,'treasury','desk','write','Balancing accounts',{i:1})],[19,20,()=>eatPlan(a,'greatHall')],[20,22,()=>stayPlan(a,'greatHall','stand','talk','Conversing in the Great Hall')],[7.5,8,()=>stayPlan(a,'treasury','stand','stand','Opening the treasury')]])());
registerPlanner('scribe',(a,h)=>sched(h,[[22,6.5,()=>sleepPlan(a)],[6.5,7.5,()=>eatPlan(a,'greatHall')],[7.5,9,()=>stayPlan(a,'warRoom','desk','write','Copying dispatches',{i:0})],[9,12,()=>stayPlan(a,'plaza','stand','write','Recording the day\'s petitions',{i:2})],[12,13,()=>eatPlan(a,'greatHall')],[13,15,()=>stayPlan(a,'treasury','desk','write','Copying records',{i:1})],[15,17,()=>stayPlan(a,'plaza','stand','write','Recording the day\'s petitions',{i:2})],[17,19,()=>stayPlan(a,'warRoom','desk','write','Filing dispatches',{i:0})],[19,20,()=>eatPlan(a,'greatHall')],[20,22,()=>stayPlan(a,'greatHall','stand','talk','Conversing in the Great Hall')]])());

// Court heroes: attend the audience line during court hours
const audience=(a,i,label)=>stayPlan(a,'plaza','petition','stand',label,{i});
registerPlanner('steward',(a,h)=>sched(h,[[22.5,6,()=>sleepPlan(a)],[6,7,()=>eatPlan(a,'greatHall')],[7,9,()=>inspect(a,[['granary','stand',36,0,'talk','Counting the granary stores'],['kitchens','stand',30,0,'talk','Checking the kitchens'],['market','browse',28,0,'talk','Speaking with market traders']])],[9,12,()=>audience(a,4,'Waiting to present the steward\'s petition')],[12,13,()=>eatPlan(a,'greatHall')],[13,15,()=>inspect(a,[['treasury','stand',30,0,'write','Reviewing the treasury'],['granary','stand',32,0,'talk','Overseeing the granary'],['smithy','stand',26,0,'talk','Reviewing forge output']])],[15,17,()=>audience(a,4,'Attending the afternoon court')],[17,19,()=>inspect(a,[['market','browse',30,1,'talk','Reviewing market dues'],['kitchens','stand',28,0,'talk','Planning tomorrow\'s meals']])],[19,20,()=>eatPlan(a,'greatHall')],[20,22.5,()=>stayPlan(a,'greatHall','stand','talk','Conversing in the Great Hall')]])());
registerPlanner('chancellor',(a,h)=>sched(h,[[22.5,6.5,()=>sleepPlan(a)],[6.5,7.5,()=>eatPlan(a,'greatHall')],[7.5,9,()=>stayPlan(a,'warRoom','desk','write','Drafting royal correspondence',{i:0})],[9,12,()=>audience(a,3,'Waiting to advise the King')],[12,13,()=>eatPlan(a,'greatHall')],[13,15,()=>stayPlan(a,'treasury','desk','write','Studying tax charters',{i:1})],[15,17,()=>audience(a,3,'Attending the afternoon court')],[17,19,()=>stayPlan(a,'warRoom','map','talk','Consulting the war maps',{i:0})],[19,20,()=>eatPlan(a,'greatHall')],[20,22.5,()=>stayPlan(a,'greatHall','stand','talk','Conversing in the Great Hall',{i:1})]])());
registerPlanner('guildenvoy',(a,h)=>sched(h,[[22.5,6.5,()=>sleepPlan(a)],[6.5,7.5,()=>eatPlan(a,'greatHall')],[7.5,9,()=>stayPlan(a,'market','browse','talk','Meeting Crown merchants',{i:1})],[9,12,()=>audience(a,1,'Waiting to petition the Crown')],[12,13,()=>eatPlan(a,'greatHall')],[13,15,()=>stayPlan(a,'market','browse','talk','Haggling in the market',{i:2})],[15,17,()=>audience(a,1,'Waiting to petition the Crown')],[17,19,()=>stayPlan(a,'market','browse','talk','Meeting Crown merchants',{i:3})],[19,20,()=>eatPlan(a,'greatHall')],[20,22.5,()=>stayPlan(a,'greatHall','stand','talk','Conversing in the Great Hall',{i:2})]])());

// ---- lower village & farms ---------------------------------------------------------------------------------
registerPlanner('farmer',(a,h)=>{const w=isWinter();return sched(h,[[21,5,()=>sleepPlan(a)],[5,6,()=>eatPlan(a,a.home)],[6,11.5,()=>w?chores(a):fieldWork(a)],[11.5,12.5,()=>eatPlan(a,'tavern')],[12.5,17.5,()=>w?chores(a):fieldWork(a)],[17.5,20,()=>tavernSocial(a)],[20,21,()=>eatPlan(a,a.home)]])()});
registerPlanner('carter',(a,h)=>sched(h,[[20.5,5.5,()=>sleepPlan(a)],[5.5,6.5,()=>eatPlan(a,a.home)],[6.5,12,()=>a.flags.wood?carterWood(a):carterGrain(a)],[12,13,()=>eatPlan(a,'tavern')],[13,18,()=>a.flags.wood?carterWood(a):carterGrain(a)],[18,20.5,()=>tavernSocial(a)]])());
registerPlanner('woodcutter',(a,h)=>sched(h,[[20.5,5,()=>sleepPlan(a)],[5,6,()=>eatPlan(a,a.home)],[6,12,()=>plan(K('chop',a),()=>({seq:[0,1].map(k=>({place:'lumber',spot:'chop',i:a.idx+k,dur:40,pose:'chop',label:'Felling timber',prod:'wood'}))}))],[12,13,()=>eatPlan(a,a.home)],[13,18,()=>plan(K('chop',a),()=>({seq:[0,1].map(k=>({place:'lumber',spot:'chop',i:a.idx+k,dur:40,pose:'chop',label:'Felling timber',prod:'wood'}))}))],[18,20.5,()=>tavernSocial(a)]])());
registerPlanner('merchant',(a,h)=>sched(h,[[20.5,6.5,()=>sleepPlan(a)],[6.5,7.5,()=>eatPlan(a,a.home)],[7.5,17,()=>stayPlan(a,'market','stall','trade','Selling wares at the market stall',{i:a.stallIdx??a.idx,prod:'trade'})],[17,18,()=>stayPlan(a,'market','browse','talk','Closing up the stall',{i:a.idx})],[18,20.5,()=>tavernSocial(a)]])());
registerPlanner('tavernkeeper',(a,h)=>sched(h,[[1.5,9.5,()=>sleepPlan(a)],[9.5,10.5,()=>eatPlan(a,'tavern')],[10.5,24,()=>plan(K('bar',a),()=>({seq:[{place:'tavern',spot:'bar',dur:40,pose:'talk',label:'Pouring ale for patrons',prod:'ale'},{place:'tavern',spot:'stand',i:a.idx,dur:26,pose:'sweep',label:'Wiping the tables'}]}))],[0,1.5,()=>stayPlan(a,'tavern','stand','sweep','Closing the tavern')]])());
registerPlanner('barmaid',(a,h)=>sched(h,[[0,10,()=>sleepPlan(a)],[10,11,()=>eatPlan(a,'tavern')],[11,24,()=>plan(K('bar',a),()=>({seq:[{place:'tavern',spot:'stand',i:a.idx,dur:30,pose:'carry',carry:'tray',label:'Carrying ale to the tables'},{place:'tavern',spot:'bar',dur:22,pose:'talk',label:'Chatting with patrons'}]}))]])());
registerPlanner('child',(a,h)=>sched(h,[[20,7,()=>sleepPlan(a)],[7,8,()=>eatPlan(a,a.home)],[8,19,()=>plan(K('play',a),()=>({seq:[0,1,2,3].map(k=>({place:'villageSquare',spot:'play',i:a.idx+k*2,dur:16+k*4,pose:k%2?'run':'talk',label:'Playing with friends',jx:(k%3-1)*1.2}))}))],[19,20,()=>eatPlan(a,a.home)]])());
registerPlanner('villager',(a,h)=>sched(h,[[21,6,()=>sleepPlan(a)],[6,20,()=>chores(a)],[20,21,()=>eatPlan(a,a.home)]])());

// ---- Millbrook, Stonehollow, bridge, Ashwood ------------------------------------------------------------------
registerPlanner('miller',(a,h)=>sched(h,[[20.5,5.5,()=>sleepPlan(a)],[5.5,6.5,()=>eatPlan(a,a.home)],[6.5,12,()=>plan(K('mill',a),()=>({seq:[{place:'mill',spot:'mill',dur:44,pose:'mill',label:'Grinding flour at the mill',prod:'flour'},{place:'mill',spot:'store',dur:14,pose:'carry',carry:'sack',label:'Stacking flour sacks'}]}))],[12,13,()=>eatPlan(a,a.home)],[13,18,()=>plan(K('mill',a),()=>({seq:[{place:'mill',spot:'mill',dur:44,pose:'mill',label:'Grinding flour at the mill',prod:'flour'},{place:'mill',spot:'store',dur:14,pose:'carry',carry:'sack',label:'Stacking flour sacks'}]}))],[18,20.5,()=>stayPlan(a,a.home,'seat','sit','Resting at home')]])());
registerPlanner('mbfarmer',(a,h)=>{const w=isWinter();return sched(h,[[20.5,5,()=>sleepPlan(a)],[5,6,()=>eatPlan(a,a.home)],[6,12,()=>w?stayPlan(a,a.home,'seat','sit','Mending tools indoors'):plan(K('mbf',a),()=>({seq:[0,1,2].map(k=>({place:'mbfield',spot:'hoe',i:a.idx+k,dur:36,pose:'hoe',label:'Working the Millbrook plots'}))}))],[12,13,()=>eatPlan(a,a.home)],[13,18,()=>w?stayPlan(a,a.home,'seat','sit','Mending tools indoors'):plan(K('mbf',a),()=>({seq:[0,1,2].map(k=>({place:'mbfield',spot:'hoe',i:a.idx+k,dur:36,pose:'hoe',label:'Working the Millbrook plots'}))}))],[18,20.5,()=>stayPlan(a,a.home,'seat','sit','Resting at home')]])()});
registerPlanner('miner',(a,h)=>sched(h,[[20,5.5,()=>sleepPlan(a)],[5.5,6.5,()=>eatPlan(a,a.home)],[6.5,12,()=>plan(K('dig',a),()=>({seq:[0,1,2].map(k=>({place:'mine',spot:'dig',i:a.idx+k,dur:40,pose:'chop',label:'Digging iron ore',prod:'ore'}))}))],[12,13,()=>eatPlan(a,a.home)],[13,17.5,()=>plan(K('dig2',a),()=>({seq:[{place:'mine',spot:'cart',dur:30,pose:'carry',carry:'crate',label:'Hauling ore to the smelter'},{place:'smelter',spot:'forge',dur:34,pose:'hammer',label:'Working the smelter',prod:'ore'}]}))],[17.5,20,()=>stayPlan(a,'mine','cart','talk','Trading tales at the mine')]])());
registerPlanner('guildmaster',(a,h)=>sched(h,[[21,6.5,()=>sleepPlan(a)],[6.5,7.5,()=>eatPlan(a,a.home)],[7.5,18,()=>inspect(a,[['mine','dig',36,0,'talk','Inspecting the ore seams'],['smelter','stand',30,0,'talk','Checking the smelter'],['mine','cart',26,0,'write','Counting ore carts']])],[18,21,()=>stayPlan(a,a.home,'seat','sit','Reviewing guild accounts')]])());
registerPlanner('caravaner',(a,h)=>sched(h,[[20,5.5,()=>sleepPlan(a)],[5.5,7,()=>eatPlan(a,a.home)],[7,18,()=>stayPlan(a,'mine','cart','carry','Loading the iron caravan',{carry:'crate'})],[18,20,()=>stayPlan(a,'mine','cart','sit','Resting by the carts')]])());
registerPlanner('merc',(a,h)=>sched(h,[[2,9,()=>stayPlan(a,'ash','sleep','sleep','Sleeping in a bedroll',{y:.15})],[9,10,()=>stayPlan(a,'ash','fire','sit','Eating by the campfire',{hook:'social'})],[10,14,()=>plan(K('mspar',a),()=>({seq:[0,1,2].map(k=>({place:'ash',spot:'camp',i:a.idx+k,dur:22,pose:k%2?'drill':'talk',label:'Sparring and sharpening steel'}))}))],[14,15,()=>stayPlan(a,'ash','fire','sit','Eating by the campfire')],[15,20,()=>plan(K('mfire',a),()=>({seq:[{place:'ash',spot:'fire',i:a.idx,dur:44,pose:'sit',label:'Drinking around the fire'},{place:'ash',spot:'camp',i:a.idx,dur:20,pose:'talk',label:'Boasting of past sieges'}]}))],[20,2,()=>stayPlan(a,'ash','fire','sit','Singing around the fire',{i:a.idx})]])());

// ---- Blackmere civilians -----------------------------------------------------------------------------------
registerPlanner('vservant',(a,h)=>sched(h,[[21,5.5,()=>stayPlan(a,'bmBarracks','bed','sleep','Asleep',{i:a.idx,y:.5})],[5.5,7,()=>stayPlan(a,'bmHall','seat','sit','Eating',{hook:'social'})],[7,21,()=>plan(K('vserv',a),()=>({seq:[{place:'bmHall',spot:'stand',i:a.idx,dur:30,pose:'sweep',label:'Cleaning the hall'},{place:'bmKeep',spot:'stand',dur:26,pose:'carry',carry:'tray',label:'Serving Lord Maren'}]}))]])());
registerPlanner('vsmith',(a,h)=>sched(h,[[21,5.5,()=>stayPlan(a,'bmSmith','stand','sleep','Asleep',{y:.4})],[5.5,21,()=>plan(K('vsm',a),()=>({seq:[{place:'bmSmith',spot:'forge',dur:24,pose:'stand',label:'Working the bellows',prod:'varms'},{place:'bmSmith',spot:'anvil',dur:44,pose:'hammer',label:'Forging weapons for Blackmere',prod:'varms'}]}))]])());
export const _sched=sched;